### ISSUE TITLE
magento.ini not loaded

### ISSUE THREAD

**Issue by bennypowers** [outeredge/edge-docker-magento#5]
on install, magento complains that soap, gd and mcrypt are not loaded.

appending the following to /usr/local/etc/php/php.ini fixes it

```
extension=gd.so
extension=mcrypt.so
extension=soap.so
```

**Comment by davidwindell** [comment]
I'm not able to reproduce this, the magento.ini file seems to be loaded for me. What is the output of `phpinfo()` for you and which version are you running?
