### ISSUE TITLE
How to use COMPOSER_AUTH during docker-composer up

### ISSUE THREAD

**Issue by VivekShingala** [outeredge/edge-docker-magento#8]
Hi

I am trying to build the container but it is throwing below error and command fails. What should be the value for COMPOSER_AUTH arg?

WARNING: The COMPOSER_AUTH variable is not set. Defaulting to a blank string.

[Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate

**Comment by davidwindell** [comment]
@VivekShingala do you need to build the container? If you extend from it with `FROM outeredge/edge-docker-magento:2.3.3` you won't need COMPOSER_AUTH.

**Comment by VivekShingala** [comment]
Yes, I am extending it from edge-docker-magento:2.3.3 but it fails with the Composer\Downloader\TransportException exception.

I have set COMPOSER_AUTH in Dockerfile like this.

ARG COMPOSER_AUTH="{\"http-basic\": {\"repo.magento.com\": {\"username\": \"0dc7d235c0e64e26857941f06\", \"password\": \"4829597ecde3311416488cb66\"}}}"

**Comment by VivekShingala** [comment]
@davidwindell  

Thank you for this repository and thank you for your prompt response.

Using FROM outeredge/edge-docker-magento:2.3.3 worked for me.

**Comment by davidwindell** [comment]
Great!
